DIGITALNOTE_VERSION = 1.0.3.4

win32 {
	DIGITALNOTE_LIB_DIR = $$DIGITALNOTE_PATH/../libs
	DIGITALNOTE_LIB_BOOST_NAME = boost_1_75_0
	DIGITALNOTE_LIB_BOOST_SUFFIX = -mgw7-mt-d-x64-1_75
	DIGITALNOTE_LIB_OPENSSL_NAME = openssl-1.0.2u
	DIGITALNOTE_LIB_BDB_NAME = db-6.2.32.NC
	DIGITALNOTE_LIB_EVENT_NAME = libevent-2.1.11-stable
	DIGITALNOTE_LIB_GMP_NAME = gmp-6.2.1
	DIGITALNOTE_LIB_MINIUPNP_NAME = miniupnpc-2.1
}
