#ifndef CCHAINPARAMS_BASE58TYPE_H
#define CCHAINPARAMS_BASE58TYPE_H

enum CChainParams_Base58Type
{
	PUBKEY_ADDRESS,
	SCRIPT_ADDRESS,
	SECRET_KEY,
	STEALTH_ADDRESS,
	EXT_PUBLIC_KEY,
	EXT_SECRET_KEY,
	MAX_BASE58_TYPES
};

#endif // CCHAINPARAMS_BASE58TYPE_H
