/* confdefs.h */
#define PACKAGE_NAME "libsecp256k1"
#define PACKAGE_TARNAME "libsecp256k1"
#define PACKAGE_VERSION "0.1"
#define PACKAGE_STRING "libsecp256k1 0.1"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "libsecp256k1"
#define VERSION "0.1"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE___INT128 1
#define HAVE_BUILTIN_EXPECT 1
#define HAVE_LIBGMP 1
#define USE_ASM_X86_64 1
#define USE_FIELD_5X52 1
#define HAVE_LIBGMP 1
#define USE_NUM_GMP 1
#define USE_FIELD_INV_NUM 1
#define USE_SCALAR_INV_NUM 1
#define USE_SCALAR_4X64 1
#define HAVE_LIBCRYPTO 1
#define USE_ECMULT_STATIC_PRECOMPUTATION 1
#define ENABLE_MODULE_RECOVERY 1
