#ifdef __cplusplus
	#include "compat.h"
	
	#include <string>
    #include <set>
    #include <map>
	#include <list>
    #include <vector>
    #include <algorithm>
    #include <cmath>
    #include <cassert>
    #include <cstddef>
    #include <cstdint>
    #include <cstdlib>
	#include <functional>
	#include <string.h>
	#include <limits>
	#include <stdexcept>
	#include <memory>
	
	#ifdef QT_GUI
		#include <QApplication>
		#include <QMenuBar>
		#include <QMenu>
		#include <QIcon>
		#include <QVBoxLayout>
		#include <QToolBar>
		#include <QStatusBar>
		#include <QLabel>
		#include <QMessageBox>
		#include <QMimeData>
		#include <QProgressBar>
		#include <QProgressDialog>
		#include <QStackedWidget>
		#include <QDateTime>
		#include <QMovie>
		#include <QFileDialog>
		#include <QDesktopServices>
		#include <QTimer>
		#include <QDragEnterEvent>
		#include <QUrl>
		#include <QMimeData>
		#include <QStyle>
		#include <QToolButton>
		#include <QScrollArea>
		#include <QScroller>
		#include <QTextDocument>
		#include <QInputDialog>
	#endif // QT_GUI
	
	#include "json/json_spirit_reader_template.h"
	#include "json/json_spirit_writer_template.h"
	#include "json/json_spirit_utils.h"
	#include "json/json_spirit_value.h"
	
	#include "types/ctxdestination.h"
	#include "types/cryptedkeymap.h"
	#include "types/data_chunk.h"
	#include "types/ec_point.h"
	#include "types/isminefilter.h"
	#include "types/mapprevtx.h"
	#include "types/mapvalue_t.h"
	#include "types/txitems.h"
	#include "types/txpair.h"
	#include "types/valtype.h"
	#include "types/vector_uchar.h"
	
	#include "enums/cchainparams_base58type.h"
	#include "enums/cchainparams_network.h"
	#include "enums/dberrors.h"
	#include "enums/isminetype.h"
	#include "enums/opcodetype.h"
	#include "enums/script_error.h"
	#include "enums/script_verify.h"
	#include "enums/sighash.h"
	#include "enums/txnouttype.h"
	
	#include "thread.h"
	#include "thread/cmutexlock.h"
	#include "thread/safety.h"
	
	#include "allocators.h"
	#include "allocators/zero_after_free_allocator.h"
	#include "allocators/secure_allocator.h"
	#include "allocators/securestring.h"
	
	#include "cbignum.h"
	#include "cdigitalnoteaddress.h"
	#include "cdigitalnotesecret.h"
	#include "caddrinfo.h"
	#include "blocksizecalculator.h"
	#include "checkpoints.h"
	#include "hash.h"
	#include "cregtestparams.h"
	#include "ccrypter.h"
	#include "txdb.h"
	#include "txdb-leveldb.h"
	#include "util.h"
	#include "serialize.h"
	#include "ckey.h"
	#include "cactivemasternode.h"
	#include "ctestnetparams.h"
	#include "cmainparams.h"
	#include "cblock.h"
	#include "caccountingentry.h"
	#include "cdb.h"
	#include "spork.h"
	#include "mnengine_extern.h"
	#include "calert.h"
	#include "tinyformat.h"
	#include "instantx.h"
	#include "cunsignedalert.h"
	#include "velocity.h"
	#include "fork.h"
	#include "chainparams.h"
	#include "cchainparams.h"
	#include "genesis.h"
	#include "caddress.h"
	#include "mining.h"
	#include "ckeyid.h"
	#include "cscriptid.h"
	#include "ctransactionlock.h"
	#include "cstealthaddress.h"
	#include "ctxindex.h"
	#include "cmasternodepayments.h"
	#include "csporkmanager.h"
	#include "cdiskblockindex.h"
	#include "cblockindex.h"
	#include "cinv.h"
	#include "coutpoint.h"
	#include "stealth.h"
	#include "cmnenginesigner.h"
	#include "cdnsseeddata.h"
	#include "cvalidationstate.h"
	#include "cmessageheader.h"
	#include "cdiskblockpos.h"
	#include "cdisktxpos.h"
	#include "comparebypriority.h"
	#include "version.h"
	#include "init.h"
	#include "coutput.h"
	#include "db.h"
	#include "masternode-payments.h"
	#include "webwalletconnector.h"
	#include "ecwrapper.h"
	#include "limitedmap.h"
	#include "mruset.h"
	#include "csporkmessage.h"
	#include "cwalletscanstate.h"
	#include "cblocklocator.h"
	#include "cmasterkey.h"
	#include "ckeypool.h"
	#include "creservekey.h"
	#include "cscriptnum.h"
	#include "caccount.h"
	#include "cextpubkey.h"
	#include "cstealthkeymetadata.h"
	#include "cpubkey.h"
	#include "signaturechecker.h"
	#include "cscriptcompressor.h"
	#include "ckeystoreisminevisitor.h"
	#include "cscriptvisitor.h"
	#include "strlcpy.h"
	#include "chash160.h"
	#include "chash256.h"
	#include "kernel.h"
	#include "blockparams.h"
	#include "main_const.h"
	#include "scrypt.h"
	#include "chainparamsseeds.h"
	#include "ckeymetadata.h"
	#include "miner.h"
	#include "seedspec6.h"
	#include "wallet.h"
	#include "chashwriter.h"
	#include "pbkdf2.h"
	#include "hmac_sha512_ctx.h"
	#include "secp256k1_context_verify.h"
	#include "smsg_const.h"
	#include "annotatedmixin.h"
	#include "cnodestination.h"
	#include "protocol.h"
	#include "addrman.h"
	#include "cinpoint.h"
	#include "clientversion.h"
	#include "cnodestatestats.h"
	#include "ctxoutcompressor.h"
	#include "eccverifyhandle.h"
	#include "masternode.h"
	#include "masternodeman.h"
	#include "message_start_size.h"
	#include "mnengine.h"
	#include "pubkey.h"
	
	#include "net/cservice.h"
	#include "net/csubnet.h"
	#include "net/cnetaddr.h"
	#include "net/cbanentry.h"
	#include "net/banreason.h"
	#include "net/network.h"
	#include "net/have_msg_nosignal.h"
	#include "net/myclosesocket.h"
	#include "net/proxytype.h"
	
	#include "smsg/ckeyid_b.h"
	#include "smsg/stored.h"
	#include "smsg/messagedata.h"
	#include "smsg/db.h"
	#include "smsg/batchscanner.h"
	#include "smsg/address.h"
	#include "smsg/bucket.h"
	#include "smsg/crypter.h"
	#include "smsg/token.h"
	#include "smsg/securemessage.h"
	#include "smsg/options.h"
	
	#include "uint/uint160.h"
	#include "uint/uint256.h"
	#include "uint/uint512.h"
#endif // __cplusplus