#ifdef __cplusplus
	/*
	#include <QApplication>
	#include <QMenuBar>
	#include <QMenu>
	#include <QIcon>
	#include <QVBoxLayout>
	#include <QToolBar>
	#include <QStatusBar>
	#include <QLabel>
	#include <QMessageBox>
	#include <QMimeData>
	#include <QProgressBar>
	#include <QProgressDialog>
	#include <QStackedWidget>
	#include <QDateTime>
	#include <QMovie>
	#include <QFileDialog>
	#include <QDesktopServices>
	#include <QTimer>
	#include <QDragEnterEvent>
	#include <QUrl>
	#include <QMimeData>
	#include <QStyle>
	#include <QToolButton>
	#include <QScrollArea>
	#include <QScroller>
	#include <QTextDocument>
	#include <QInputDialog>
	*/
	/*
	#include <boost/date_time/posix_time/posix_time.hpp>
	#include <boost/algorithm/string/case_conv.hpp>
	#include <boost/algorithm/string/join.hpp>
	#include <boost/algorithm/string/predicate.hpp>
	#include <boost/program_options/detail/config_file.hpp>
	#include <boost/program_options/parsers.hpp>
	#include <boost/filesystem.hpp>
	#include <boost/filesystem/fstream.hpp>
	#include <boost/foreach.hpp>
	//#include <boost/thread.hpp>
	//#include <boost/bind.hpp>
	*/
	
	#include <string>
    #include <set>
    #include <map>
    #include <memory>
    #include <vector>
    #include <unordered_map>
    #include <array>
    #include <bitset>
    #include <initializer_list>
    #include <functional>
    #include <algorithm>
    #include <numeric>
    #include <iterator>
    #include <type_traits>
    #include <cmath>
    #include <cassert>
    #include <cfloat>
    #include <complex>
    #include <cstddef>
    #include <cstdint>
    #include <cstdlib>
    #include <mutex>
    #include <thread>
    #include <condition_variable>
	
	#include "activemasternode.h"
	#include "addrman.h"
	#include "allocators.h"
	#include "annotatedmixin.h"
	#include "base58.h"
	#include "bignum.h"
	#include "blockparams.h"
	#include "blocksizecalculator.h"
	#include "caccount.h"
	#include "caccountingentry.h"
	#include "caddress.h"
	#include "caddrinfo.h"
	#include "caddrman.h"
	#include "caffectedkeysvisitor.h"
	#include "calert.h"
	#include "cbasickeystore.h"
	#include "cblock.h"
	#include "cblockindex.h"
	#include "cblocklocator.h"
	#include "cchainparams.h"
	#include "cconsensusvote.h"
	#include "ccriticalblock.h"
	#include "ccriticalsection.h"
	#include "ccrypter.h"
	#include "ccryptokeystore.h"
	#include "cdbenv.h"
	#include "cdb.h"
	#include "cdiskblockindex.h"
	#include "cdiskblockpos.h"
	#include "cdisktxpos.h"
	#include "cdnsseeddata.h"
	#include "cextkey.h"
	#include "cextpubkey.h"
	#include "chain.h"
	#include "chainparams.h"
	#include "chainparamsseeds.h"
	#include "chash160.h"
	#include "chash256.h"
	#include "chashwriter.h"
	#include "checkpoints.h"
	#include "cinpoint.h"
	#include "cinv.h"
	#include "ckey.h"
	#include "ckeyid.h"
	#include "ckeymetadata.h"
	#include "ckeypool.h"
	#include "ckeystore.h"
	#include "ckeystoreisminevisitor.h"
	#include "clientversion.h"
	#include "cmainparams.h"
	#include "cmainsignals.h"
	#include "cmasterkey.h"
	#include "cmerkletx.h"
	#include "cmessageheader.h"
	#include "cmutexlock.h"
	#include "cnodestatestats.h"
	#include "coincontrol.h"
	#include "comparebypriority.h"
	#include "comparevalueonly.h"
	#include "compat.h"
	#include "coutpoint.h"
	#include "coutput.h"
	#include "cprivkey.h"
	#include "cpubkey.h"
	#include "cregtestparams.h"
	#include "creservekey.h"
	#include "crypter.h"
	#include "cscriptcompressor.h"
	#include "cscript.h"
	#include "cscriptid.h"
	#include "cscriptnum.h"
	#include "cscriptvisitor.h"
	#include "csecret.h"
	//#include "csignaturecache.h"
	#include "csporkmanager.h"
	#include "csporkmessage.h"
	#include "cstealthaddress.h"
	#include "cstealthkeymetadata.h"
	#include "ctestnetparams.h"
	#include "ctransaction.h"
	#include "ctransactionlock.h"
	#include "ctxindex.h"
	#include "ctxin.h"
	#include "ctxoutcompressor.h"
	#include "ctxout.h"
	#include "cunsignedalert.h"
	#include "cvalidationstate.h"
	#include "cwallet.h"
	#include "cwalletinterface.h"
	#include "cwalletkey.h"
	#include "cwalletscanstate.h"
	#include "cwallettx.h"
	#include "dberrors.h"
	#include "db.h"
	#include "eccverifyhandle.h"
	#include "ecwrapper.h"
	#include "fork.h"
	#include "genesis.h"
	#include "hash.h"
	#include "hmac_sha512_ctx.h"
	#include "init.h"
	#include "instantx.h"
	#include "kernel.h"
	#include "key.h"
	#include "keystore.h"
	#include "limitedmap.h"
	#include "main_const.h"
	#include "main_extern.h"
	#include "main.h"
	#include "mapvalue_t.h"
	#include "masternodeconfig.h"
	#include "masternode.h"
	#include "masternodeman.h"
	#include "masternode-payments.h"
	#include "message_start_size.h"
	#include "miner.h"
	#include "mining.h"
	#include "mnengine.h"
	#include "mruset.h"
	#include "netbase.h"
	#include "net.h"
	#include "pbkdf2.h"
	#include "protocol.h"
	#include "pubkey.h"
	#include "rpcclient.h"
	#include "rpcprotocol.h"
	#include "rpcserver.h"
	#include "rpcvelocity.h"
	#include "script.h"
	#include "scrypt.h"
	#include "secp256k1_context_verify.h"
	#include "seedspec6.h"
	#include "serialize.h"
	#include "signaturechecker.h"
	#include "smsg_const.h"
	#include "smsg_extern.h"
	#include "smsg.h"
	#include "spork.h"
	#include "stealth.h"
	#include "strlcpy.h"
	#include "sync.h"
	#include "threadsafety.h"
	#include "tinyformat.h"
	#include "txdb.h"
	#include "txdb-leveldb.h"
	#include "txmempool.h"
	#include "ui_interface.h"
	#include "util.h"
	#include "velocity.h"
	#include "version.h"
	#include "walletdb.h"
	#include "wallet.h"
	#include "webwalletconnector.h"
#endif // __cplusplus